describe("Login and Access Profile", () => {
  it("should not log in with invalid credentials and show an alert message", () => {
    // Visit the login page or the page where the login functionality is located
    cy.visit("http://127.0.0.1:5500/");

    // Ensure the parent modal is made visible before interacting with the child elements
    cy.get("#loginModal").should("have.css", "display", "none").invoke("show"); // This assumes you are using Bootstrap modal

    // Scroll to the loginEmail input field to make it visible
    cy.get("#loginEmail").scrollIntoView();

    // Now, interact with the login form with invalid credentials
    cy.get("#loginForm").click();

    // Use { force: true } for typing into the email and password input fields
    cy.get("#loginEmail").type("invalidemail@example.com", { force: true });
    cy.get("#loginPassword").type("invalidpassword", { force: true });

    cy.get("#loginForm").submit();

    // Handle the alert generated by window.alert()
    cy.handleAlert();
  });
});
