name: Automated E2E Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Set up ngrok
        run: |
          npm install -g ngrok
          ngrok http 5500 > /dev/null &
          sleep 10
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
          echo "ngrok URL: $NGROK_URL"
          echo "::set-output name=ngrok-url::$NGROK_URL"

      - name: Wait for ngrok and run Cypress tests
        run: |
          n=0
          until [ $n -ge 5 ]
          do
            curl -I $NGROK_URL && break
            n=$[$n+1]
            sleep 30
          done
          npm run test-e2e-cli
        env:
          NGROK_URL: ${{ steps.ngrok.outputs.ngrok-url }}
