name: Automated E2E Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Start server
        run: |
          npm start &

          # Install and start ngrok
          npm install -g ngrok
          ngrok http 5500 -host-header="localhost:5500" > /dev/null &

          # Wait for ngrok to generate a public URL
          sleep 10

          # Display the ngrok URL for debugging
          echo "ngrok URL: $(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          config-file: "./cypress.json"
          start: true
          wait-on: ${{ steps.ngrok.outputs.url }}
          wait-on-timeout: 60
